[deploy]
startCommand = "pip install -r backend/requirements.txt && cd backend && PYTHONPATH=/app/backend alembic upgrade head && PYTHONPATH=/app/backend uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10