[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
name = "chatbot-ai-backend"

[environments.production.variables]
ENVIRONMENT = "production"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"