[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
name = "detailchatbot-backend"

[environments.production.variables]
ENVIRONMENT = "production"